### ISSUE TITLE
mysql specific functions in custom sql

### ISSUE THREAD

**Issue by danmarsden** [SN-RECIT-formation-a-distance/moodle-local_recitdashboard#3]
I see many sql queries in your code which use mysql specific functions - not avaialble in other database types that moodle supports.

Please note that at a bare minimum, plugins submitted to the plugins database must support both mysql/mariadb and Postgresql databases.

**Comment by emilevirus** [comment]
Hello,

Thank you for your comment.

This plugin was initially designed for MySQL. We looked into supporting Postgres, but it'd require a rewrite of almost all queries as we use MySQL-specific functions and rather complex queries. As this plugin is already in production and used by many Moodle sites, we're worried that changing queries too much may affect the results.

We read in Moodle docs that you may accept a plugin even if it only supports one database. So we added this cross-DB limitation in the readme file.

**Comment by danmarsden** [comment]
our plugin contribution checklist states this:

At very least, the plugin is supposed to work with MySQL and PostgreSQL unless reasons are clearly explained in the description and the README file (such as the plugin is a wrapper for third-party DB specific utility).

A good example of this is:
https://moodle.org/plugins/search_postgresfulltext

In my personal opinion - your reason "we don't want to do this because it will require us to do some work." - is not good enough but I will check in with the wider plugin review team to get you a final decision.

thanks.

**Comment by danmarsden** [comment]
Hi there,

The Plugin review team has discussed this and we are unable to relax the guidelines for this plugin.

It puts a bad light on Moodle and the plugins directory when someone tries to install a plugin that breaks their site or just doesn't work when they use PostgreSQL. We are not as strict as Moodle core which also requires all code to also support Microsoft Sql and Oracle - for approval in the plugins db we only require MySQL and PostgreSQL support.

Some of the issues I saw are with formatting time and dates at the SQL layer which is problematic anyway as it causes problems when users are in different timezones.

Feel free to share a link to your github repository in the moodle forums - but if you would like to list this plugin within the moodle.org plugins db, you will need to fix the sql statements in your plugin to comply with our guidelines and support both Mysql and PostgreSQL before we can approve this.

thanks!
