### ISSUE TITLE
missing gpl boilerplate from most files

### ISSUE THREAD

**Issue by danmarsden** [SN-RECIT-formation-a-distance/moodle-local_recitdashboard#4]
see: https://docs.moodle.org/dev/Plugin_contribution_checklist#Licensing

**Comment by emilevirus** [comment]
I found one missing file with a missing license. However, you mentioned it was 'most files'. Did I miss something here?

**Comment by danmarsden** [comment]
if you run your code through our local_codechecker and local_moodlecheck plugins it will report where it's missing.

**Comment by emilevirus** [comment]
Fixed with 25713aea18395973c9015e97314d7601e1662cd2
